# Base stage
FROM node:18-alpine AS base
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install --legacy-peer-deps

# Copy application code
COPY . .

# Production stage
FROM base AS production
RUN npm run build

# Serve the application using Nginx
FROM nginx:alpine AS final
COPY --from=production /app/dist /usr/share/nginx/html
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
