services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    command: >
      sh -c "python manage.py migrate && gunicorn backend.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    environment:
      DJANGO_ENV: production
      DEBUG: 'False'
    ports:
      - "8000:8000"
    env_file:
      - .env.production
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: postgres
    volumes: 
    - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

volumes:
  postgres_data:
