# Base image
FROM python:3.11.4 AS base
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    libpq-dev \
    && apt-get clean

# Install Python dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY . .

# Development stage
FROM base AS development
ENV DJANGO_ENV=development
EXPOSE 8000
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
